# Generated by Django 4.1.4 on 2024-01-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
