# Generated by Django 4.1.4 on 2024-01-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept',
            new_name='department',
        ),
    ]
